openapi: 3.0.1
info:
  title: "Ecosyste.ms: Sponsors"
  description: "An open API service aggregating public data about GitHub Sponsors."
  contact:
    name: Ecosyste.ms
    email: support@ecosyste.ms
    url: https://ecosyste.ms 
  version: 1.0.0
  license:
    name: CC-BY-SA-4.0
    url: https://creativecommons.org/licenses/by-sa/4.0/
externalDocs:
  description: GitHub Repository
  url: https://github.com/ecosyste-ms/sponsors
servers:
- url: https://sponsors.ecosyste.ms/api/v1
paths:
  /accounts:
    get:
      summary: "List Accounts"
      description: "List all maintainer accounts."
      operationId: listAccounts
      parameters:
        - name: page
          in: query
          description: pagination page number 
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          description: Number of records to return 
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: "A list of accounts."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
        '404':
          description: "No accounts found."
  /accounts/{login}:
    get:
      summary: "Get Account"
      description: "Get an account by login."
      operationId: getAccount
      parameters:
      - name: login
        in: path
        description: "The login name for the account."
        required: true
        schema:
          type: string
      responses:
        '200':
          description: "An account."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        '404':
          description: "Account not found."
  /account/{login}/sponsors:
    get:
      summary: "List Account Sponsors"
      description: "List all sponsors for an account."
      operationId: listAccountSponsors
      parameters:
        - name: login
          in: path
          description: "The login name for the account."
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: pagination page number 
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          description: Number of records to return 
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: "A list of sponsors."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sponsorship"
        '404':
          description: "No sponsors found."
  /account/{login}/sponsorships:
    get:
      summary: "List Account Sponsorships"
      description: "List all sponsorships for an account."
      operationId: listAccountSponsorships
      parameters:
        - name: login
          in: path
          description: "The login name for the account."
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: pagination page number 
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          description: Number of records to return 
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: "A list of sponsorships."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sponsorship"
        '404':
          description: "No sponsorships found."
  /sponsors:
    get:
      summary: "List Sponsors"
      description: "List all sponsors."
      parameters:
        - name: page
          in: query
          description: pagination page number 
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          description: Number of records to return 
          required: false
          schema:
            type: integer
      operationId: listSponsors
      responses:
        '200':
          description: "A list of sponsors."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
        '404':
          description: "No sponsors found."

components:
  schemas:
    Account:
      required:
        - id
        - login
        - has_sponsors_listing
        - data
        - created_at
        - updated_at
        - last_synced_at
        - sponsors_count
        - sponsorships_count
        - active_sponsorships_count
        - sponsor_profile
        - url
        - api_url
        - html_url
        - sponsors_url
        - sponsors_api_url
        - sponsorships_api_url
        - minimum_sponsorship_amount
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "The unique identifier for the account."
        login:
          type: string
          description: "The login name for the account."
        has_sponsors_listing:
          type: boolean
          description: "Indicates if the account has a sponsors listing."
        data:
          type: object
          description: "The raw data for the account."
        created_at:
          type: string
          format: date-time
          description: "The date and time the account was created."
        updated_at:
          type: string
          format: date-time
          description: "The date and time the account was last updated."
        last_synced_at:
          type: string
          format: date-time
          description: "The date and time the account was last synced."
        sponsors_count:
          type: integer
          format: int64
          description: "The number of sponsors for the account."
        sponsorships_count:
          type: integer
          format: int64
          description: "The number of sponsorships for the account."
        active_sponsorships_count:
          type: integer
          format: int64
          description: "The number of active sponsorships for the account."
        sponsor_profile:
          type: object
          description: "The sponsor profile for the account."
        url:
          type: string
          description: "The URL for the account."
        api_url:
          type: string
          description: "The API URL for the account."
        html_url:
          type: string
          description: "The HTML URL for the account."
        sponsors_url:
          type: string
          description: "The sponsors URL for the account."
        sponsors_api_url:
          type: string
          description: "The sponsors API URL for the account."
        sponsorships_api_url:
          type: string
          description: "The sponsorships API URL for the account."
        minimum_sponsorship_amount:
          type: integer
          format: int64
          description: "The minimum sponsorship amount for the account."
    Sponsorship:
      required:
        - id
        - status
        - created_at
        - updated_at
        - funder
        - maintainer
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "The unique identifier for the sponsorship."
        status:
          type: string
          description: "The status of the sponsorship."
        created_at:
          type: string
          format: date-time
          description: "The date and time the sponsorship was created."
        updated_at:
          type: string
          format: date-time
          description: "The date and time the sponsorship was last updated."
        funder:
          $ref: "#/components/schemas/Account"
        maintainer:
          $ref: "#/components/schemas/Account"
          
